language: java
sudo: false

cache:
  directories:
  - $HOME/.m2
  
matrix:
  include:
    - env: PROFILES='-P osgi-tests'
      jdk: oraclejdk8
    - env: PROFILES=''
      jdk: oraclejdk11
    - env: PROFILES=''
      jdk: openjdk12

script:
  - echo JAVA_HOME = ${JAVA_HOME}
  - mvn clean install -B $PROFILES