language: java
sudo: false

cache:
  directories:
  - $HOME/.m2
  
matrix:
  include:
    - env: PROFILES='osgi-tests'
      jdk: oraclejdk8
    - env: PROFILES=' '
      jdk: oraclejdk11

script:
  - echo JAVA_HOME = ${JAVA_HOME}
  - mvn clean install -B -P $PROFILES